title: Jordan De Visser
description: Blogging about my software projects
remote_theme: jekyll/minima
permalink: /:categories/:year/:month/:day/:title
timezone: Australia/Brisbane

plugins:
  - jekyll-remote-theme

minima:
  skin: solarized-dark
  show_excerpts: true